// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.28"
	GitCommit   = "9f7fb29" // the commit JUST BEFORE the release
	VersionDate = "2021-01-13 11:22" // UTC
)

