// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.31"
	GitCommit   = "ee4715a" // the commit JUST BEFORE the release
	VersionDate = "2021-03-19 21:25" // UTC
)

