// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package leabra

const (
	Version     = "v1.1.26"
	GitCommit   = "be91483" // the commit JUST BEFORE the release
	VersionDate = "2021-01-04 01:33" // UTC
)

